### ISSUE TITLE
Update CI to use Solutions & Portable DebugTypes

### ISSUE THREAD

**Issue by carusology** [invio/Invio.Xunit#12]
**Background**
As part of our migration to v1.0.4 of the .NET SDK, I [set the `DebugType` to `full`](https://github.com/invio/Invio.Xunit/commit/d9f1c4decc3de11c275064b060061e3b5dbdaf98#diff-d73830733f04de40e055ef8a223b72f8R8) and updated the CI scripts to explicitly reference XML-based `*.csproj` files due to the removal of `global.json` and `project.json`. The `DebugType` really should be `portable` for .NET Core when we pack the code (though it needs to be `full` for when we run opencover on it), and we should add a `*.sln` to manage our `*.csproj` files.

**Task**
* [ ] Update the repository to have a `Invio.Xunit.sln` solution at the root of the repository that references the source and test projects.
* [ ] Update `Invio.Xunit.Tests.csproj` such that `<IsPackable>false</IsPackable>` is specified.
* [ ] Restore `set-debug-type.ps1`, but with it updating the `DebugType` via the XML-based `Invio.Xunit.csproj` instead of JSON-based `project.json`.
